MAX_EXEMPTIONS_PER_YEAR = 3
MAX_PRICE_EXEMPTION = 200   # USD
MAX_WEIGHT_EXEMPTION = 20   # kg
IMPORT_FEE_PERCENT = 0.6
MINIMUM_FEE_PAYMENT = 10    # USD
M = 10000   # Big-M constant
MIN_TOLERANCE = 0.001